patient_find_button = '[title="Patient Info"]'
patient_find_field = '//input[@data-placeholder="Search for patient"]'
# '//div/div/input[@id="mat-input-0"]'
patient_click_button = '#mat-option-4'
# '//div/mat-option'
transaction_history_button = 'div [class="mat-tooltip-trigger amds-svg amds-menu-icon amds-svg-trans-entry-card"]'
writeoff_button = "#btnTxWriteOff"
writeoff_source_button = '[id="selSource"] option'
writeoff_code_field = '[id=ellWOCode] input'
visit_field = '[id="ellVisitEpisode"] input'
balance_field = 'td[class="grayed"] xslchangebalance'
amount_filed = 'input[onchange="editItem()"]'
ok_buton = '#btnOk'
cancel_button = '#btnCancel'
iframe1 = '#frmPatientInfo1'
iframe_transaction_history = 'iframe[src="https://pm-wfe-102.advancedmd.com/practicemanager/patientfiles/demo_main.html"]'
iframe_write_off = '#ifrmTabs'
